theme: jekyll-theme-cayman
title: "BuildingNet: Learning to Label 3D Buildings"
description: "ICCV 2021 (oral)"
show_downloads: false
github:
  is_project_page: true
  zip_url: https://github.com/buildingnet/buildingnet_dataset/zipball/main
  tar_url: https://github.com/buildingnet/buildingnet_dataset/tarball/main
